CREATE DATABASE IF NOT EXISTS adhd_helper DEFAULT CHARACTER SET utf8mb4;
USE adhd_helper;

CREATE TABLE IF NOT EXISTS app_state (
  id INT PRIMARY KEY,
  coins INT NOT NULL
);

INSERT INTO app_state (id, coins)
VALUES (1, 0)
ON DUPLICATE KEY UPDATE coins = coins;

CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  content VARCHAR(255) NOT NULL,
  category VARCHAR(50),
  energy INT,
  coins INT NOT NULL,
  completed TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS questions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  text VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS reward_batch (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reward_item (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  reward_text VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'earned',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_reward_batch FOREIGN KEY (batch_id) REFERENCES reward_batch(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reward_pool (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  reward_text VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
